using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Shuriken : MonoBehaviour
{
    [SerializeField] float Speed;
    [SerializeField] float RotSpeed;
    [SerializeField] GameObject ShurikenModel;

    void Start()
    {
        Destroy(this.gameObject, 1.0f);
    }

    // Update is called once per frame
    void Update()
    {
        // transform‚ğæ“¾
        Transform myTransform = this.transform;

        // À•W‚ğæ“¾
        Vector3 pos = myTransform.position;
        pos.z += Speed * Time.deltaTime;    // zÀ•W‚Ö0.01‰ÁZ

        myTransform.position = pos;  // À•W‚ğİ’è

        Transform ModelTransform = ShurikenModel.transform;

        ModelTransform.Rotate(0, RotSpeed, 0);
    }
}
